### PR TITLE
Add 2020 and 2021

### PR DESCRIPTION
**Pull request by razzeee**
This adds both latest years, the infos for 2020 are still missing.

If possible we should go back and fill in more detail, hopefully this is a good start.

### CODE REVIEW

**Comment by wagnerpeer** [comment]
Wouldn't it be nice to only have the latest year in the README.md and archive every other year in its own markdown?
If this is not an option, how about chronologically descending order (latest on top)?

**Comment by razzeee** [comment]
Both are options, but as there was no structure that would have fit multiple years, I've choosen to go with this.

I would have expected to have one repo per year, but that might be overkill at this point. At least as long as it's only a readme like file.

So I think having a file with each year and having the readme just link to each year is sensible.

**Comment by razzeee** [comment]
I've shuffled this around a bit, hopefully better now

**Review by wagnerpeer — APPROVED** [review]
Thanks for the effort to split by years.

**Comment by razzeee** [comment]
So what is needed to get this merged?

**Pull request merged**
